/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MeetingSchedule;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maxkim
 */
public class EmpMain extends javax.swing.JFrame {

    // username and passwords are received from the Login jFrame
    String username; 
    String pswd;

    /**
     * Creates new form EmpMain
     */
    public EmpMain() {
        initComponents();
    }

    // Overloaded Constructor
    // Get username and password from the Login Frame
    public EmpMain(String username, String pswd) {
        initComponents();
        myInitComponents();
        this.username = username;
        this.pswd = pswd;
        jLabelUserName.setText(username);
        
        // show new invitations
        showNewInvitations();
    }

    // This method displays a message that shows new invitations for the user
    private void showNewInvitations() {
        String query = "SELECT m.ownerID, m.topic "
                + "FROM meetings AS m "
                + "INNER JOIN assignments AS a "
                + "ON m.id = a.meetingID "
                + "WHERE a.inviteeID = '" + username + "' AND "
                + "a.acceptance = 'unchecked';";

        // connect to database 
        DBconnector db = new DBconnector();
        Connection connection = db.connectToDB();
        Statement st;
        ResultSet rs;

        int i = 0;
        Object[] row = new Object[2];
        try {
            st = connection.createStatement();
            // execute the given SQL statement and get the result
            rs = st.executeQuery(query);

            // Loops until the last row from the rows retrrieved is reached
            while (rs.next()) {
                // retrives the value of the designated column in the current row of this Result Set Object
                row[0] = rs.getString("ownerID");
                row[1] = rs.getString("topic");
                JOptionPane.showMessageDialog(null, "You hava a new meeting invitation "
                        + "from " + row[0] + ": '" + row[1] + "'.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // This method prvents from terminating an application when a JFrame is closed
    private void myInitComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jPanel1 = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCalendar = new javax.swing.JButton();
        jButtonCheckInvi = new javax.swing.JButton();
        jButtonSendMultiInvi = new javax.swing.JButton();
        jButtonSendInvi = new javax.swing.JButton();
        jButtonManageMeeting = new javax.swing.JButton();
        jButtonMeetingStatus = new javax.swing.JButton();
        jButtonChangePw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUserName.setBackground(new java.awt.Color(204, 255, 204));
        jLabelUserName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelUserName.setText("name");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Hi,");

        jButtonCalendar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonCalendar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonCalendar.setText("Calendar/Note");
        jButtonCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalendarActionPerformed(evt);
            }
        });

        jButtonCheckInvi.setBackground(new java.awt.Color(255, 204, 204));
        jButtonCheckInvi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonCheckInvi.setText("Check Meeting Invitations");
        jButtonCheckInvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInviActionPerformed(evt);
            }
        });

        jButtonSendMultiInvi.setBackground(new java.awt.Color(255, 204, 204));
        jButtonSendMultiInvi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonSendMultiInvi.setText("Available Time Slots & Send Meeting Invitation");
        jButtonSendMultiInvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMultiInviActionPerformed(evt);
            }
        });

        jButtonSendInvi.setBackground(new java.awt.Color(255, 204, 204));
        jButtonSendInvi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonSendInvi.setText("Send Meeting Invitation");
        jButtonSendInvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendInviActionPerformed(evt);
            }
        });

        jButtonManageMeeting.setBackground(new java.awt.Color(204, 255, 204));
        jButtonManageMeeting.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonManageMeeting.setText("Manage Meeting");
        jButtonManageMeeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageMeetingActionPerformed(evt);
            }
        });

        jButtonMeetingStatus.setBackground(new java.awt.Color(204, 255, 204));
        jButtonMeetingStatus.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonMeetingStatus.setText("Meeting Status");
        jButtonMeetingStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeetingStatusActionPerformed(evt);
            }
        });

        jButtonChangePw.setBackground(new java.awt.Color(255, 255, 255));
        jButtonChangePw.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonChangePw.setText("Change Paasowrd");
        jButtonChangePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSendMultiInvi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonChangePw))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCalendar)
                                    .addComponent(jButtonCheckInvi)
                                    .addComponent(jButtonSendInvi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonMeetingStatus)
                                    .addComponent(jButtonManageMeeting))))
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalendar)
                    .addComponent(jButtonManageMeeting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCheckInvi)
                    .addComponent(jButtonMeetingStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSendInvi)
                    .addComponent(jButtonChangePw))
                .addGap(26, 26, 26)
                .addComponent(jButtonSendMultiInvi)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This method activates the calendar jFrame and also passes the username
    // to the calendar jFrame
    private void jButtonCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalendarActionPerformed

        // Pass username and password to EmpMain Frame
        EmpCalendarNote empCal = new EmpCalendarNote(username);
        empCal.setVisible(true);
    }//GEN-LAST:event_jButtonCalendarActionPerformed

    // Opens the EmpCheckInvitations jFrame and pass the value of username to it
    private void jButtonCheckInviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInviActionPerformed
        EmpCheckInvitation invi = new EmpCheckInvitation(username);
        invi.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonCheckInviActionPerformed

    // This method opens up the EmpSendInvitation jFrame
    private void jButtonSendMultiInviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMultiInviActionPerformed
        EmpSendInvitation invi = new EmpSendInvitation(username);
        invi.setVisible(true);
    }//GEN-LAST:event_jButtonSendMultiInviActionPerformed

    private void jButtonSendInviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendInviActionPerformed
        EmpSendInvitationNotAva e = new EmpSendInvitationNotAva(username);
        e.setVisible(true);
    }//GEN-LAST:event_jButtonSendInviActionPerformed

    // This method opens up the EmpManageMeeting jFrame
    private void jButtonManageMeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageMeetingActionPerformed
        EmpManageMeeting empMan = new EmpManageMeeting(username);
        empMan.setVisible(true);
    }//GEN-LAST:event_jButtonManageMeetingActionPerformed

    // Opens up the EmpMeetingStatus jFrame
    private void jButtonMeetingStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeetingStatusActionPerformed
        EmpMeetingStatus e = new EmpMeetingStatus(username);
        e.setVisible(true);
    }//GEN-LAST:event_jButtonMeetingStatusActionPerformed

    private void jButtonChangePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangePwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButtonCalendar;
    private javax.swing.JButton jButtonChangePw;
    private javax.swing.JButton jButtonCheckInvi;
    private javax.swing.JButton jButtonManageMeeting;
    private javax.swing.JButton jButtonMeetingStatus;
    private javax.swing.JButton jButtonSendInvi;
    private javax.swing.JButton jButtonSendMultiInvi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
