/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MeetingSchedule;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maxkim
 */
public class RoomInsertDeleteDisplay extends javax.swing.JFrame {

    private static final String DBHOST = "localhost";
    private static final String DBNAME = "CS580_Schedule";
    private static final String DBUSER = "root";
    private static final String DBPASSWORD = "maxkim";
    private static final String CONN_STRING
            = "jdbc:mysql://" + DBHOST + "/" + DBNAME + "?user=" + DBUSER
            + "&password=" + DBPASSWORD + "&useSSL=false";
    /**
     * Creates new form RoomInsertDeleteDisplay
     */
    public RoomInsertDeleteDisplay() {
        initComponents();
        Show_Room_In_JTable();
    }

    // connect to database
    public Connection getConnection() {

        Connection con = null;
        try {
            //Load the MySQL Connector / J classes
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            //Set connect string to local MySQL database, user is JohnCena
            String connString = "jdbc:mysql://" + DBHOST + "/" + DBNAME
                    + "?user=" + DBUSER + "&" + "password=" + DBPASSWORD + "&useSSL=false";
            con = DriverManager.getConnection(connString);
            System.out.println("Database successfully connected");
           
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ArrayList<RoomDB> getRoomList()
    {
        // each roomDB object has its number and size
        ArrayList<RoomDB> roomList = new ArrayList<RoomDB>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `rooms`";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            // get the SQL query result
            rs = st.executeQuery(query);
            RoomDB room;
            while(rs.next()) {
                // store SQL result's first and second column 
                room = new RoomDB(rs.getInt("id"), rs.getInt("size"));
                // add new rooms (number, size) to the list
                roomList.add(room);
            }
            
             //Get meta data on just opened result set
            ResultSetMetaData rsMeta = rs.getMetaData();

         // Display Column names as string
            String varColNames = "";
            int varColCount = rsMeta.getColumnCount();
            for (int col = 1; col <= varColCount; col++) {
                varColNames = varColNames + rsMeta.getColumnName(col) + " ";
            }
            System.out.println(varColNames);

        //Display column values
            while (rs.next()) {
                for (int col = 1; col <= varColCount; col++) {
                    System.out.print(rs.getString(col) + " ");
                }
                System.out.println();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return roomList;
    }   
    
    // Display Data in JTable
    public void Show_Room_In_JTable()
    {
        ArrayList<RoomDB> list = getRoomList();
        DefaultTableModel model = (DefaultTableModel)jTableDisplayRooms.getModel();
        // each row has room's attributes: size and number 
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) 
        {
            row[0] = list.get(i).getNumber();
            row[1] = list.get(i).getSize();
            model.addRow(row);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRooNumber = new javax.swing.JLabel();
        LabelRoomSize = new javax.swing.JLabel();
        TxtFdRoomNum = new javax.swing.JTextField();
        TxtFdRoomSize = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisplayRooms = new javax.swing.JTable();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        LabelRooNumber.setText("Room Number:");

        LabelRoomSize.setText("Room Size:");

        TxtFdRoomNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        TxtFdRoomSize.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTableDisplayRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Size"
            }
        ));
        jScrollPane1.setViewportView(jTableDisplayRooms);

        jButtonInsert.setBackground(new java.awt.Color(204, 255, 204));
        jButtonInsert.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonInsert.setText("Insert");

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 204));
        jButtonUpdate.setText("Update");

        jButtonDelete.setBackground(new java.awt.Color(255, 153, 153));
        jButtonDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelRooNumber)
                            .addComponent(LabelRoomSize))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFdRoomNum, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(TxtFdRoomSize))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelRooNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelRoomSize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdRoomSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomInsertDeleteDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomInsertDeleteDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomInsertDeleteDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomInsertDeleteDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomInsertDeleteDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRooNumber;
    private javax.swing.JLabel LabelRoomSize;
    private javax.swing.JTextField TxtFdRoomNum;
    private javax.swing.JTextField TxtFdRoomSize;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDisplayRooms;
    // End of variables declaration//GEN-END:variables
}
